<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{dd1d77bd-4e25-4335-9864-1fdb214a75d4}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	test : UINT;
END_VAR


//DAQ test
//fssf
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//daq]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>